version: '3.8'

services:
  db:
    image: postgres:14
    container_name: household_db
    environment:
      POSTGRES_USER: household_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: household_db
    ports:
      - "5432:5432"
