ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
}
jwt {
    domain = "cyan0515.com"
    audience = "myAudience"
    realm = "myRealm"
    secret = ${?JWT_SECRET}
}
db {
    url = ${?DB_URL}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
    maximumPoolSize = 10
    maximumPoolSize = ${?DB_MAXIMUM_POOL_SIZE}
    minimumIdle = 1
    minimumIdle = ${?DB_MINIMUM_IDLE}
    connectionTimeoutMillis = 30000
    connectionTimeoutMillis = ${?DB_CONNECTION_TIMEOUT_MILLIS}
    baselineOnMigrate = false
    baselineOnMigrate = ${?DB_BASELINE_ON_MIGRATE}
}
