ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
}
jwt {
    domain = "cyan0515.com"
    audience = "myAudience"
    realm = "myRealm"
    secret = ${?JWT_SECRET}
    ttlSeconds = 3600
    ttlSeconds = ${?JWT_TTL_SECONDS}
}
db {
    url = ${?DB_URL}
    user = "household_user"
    password = ${?DB_PASSWORD}
}
